"""Add unique endpoint to pages

Revision ID: 6dbdbe20b4c3
Revises: 5069bfd46c5f
Create Date: 2020-10-02 14:38:39.291773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dbdbe20b4c3'
down_revision = '5069bfd46c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('endpoint', sa.String(length=256), nullable=True))
    op.create_unique_constraint(None, 'pages', ['endpoint'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pages', type_='unique')
    op.drop_column('pages', 'endpoint')
    # ### end Alembic commands ###
